
CREATE TABLE groovy_layers.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE groovy_layers.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  quality_setting BIGINT NOT NULL,
  file_location VARCHAR(255) NOT NULL,
  print_job_file VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  last_update VARCHAR(255) NOT NULL
);

CREATE TABLE groovy_layers.print_stations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  last_update VARCHAR(255) NOT NULL
);

CREATE TABLE groovy_layers.material_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  amount_kg DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
  material_type VARCHAR(255) NOT NULL,
  price_kg DOUBLE PRECISION DEFAULT 0.0 NOT NULL
);